apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  ports:
   - name: "http-port"
     protocol: "TCP"
     port: 50002
     targetPort: 8080
  selector:
    app: demo-deploy
  type: ClusterIP
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-deploy
  template:
    metadata:
      labels:
        app: demo-deploy
    spec:
      containers:
      - name: demo-image
        #image: demo-app
        #imagePullPolicy: Never
        image: 12010908/demo-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: docker-secret

